name: test
on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18.16.0-alpine3.17

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --ignore-scripts --no-package-lock --no-audit --no-fund
      - name: Test tests
        run: npm run test
      - name: Check dependencies
        run: npm audit
      # - name: Test coverage
      #   run: yarn test:cov
